application: bwreher-tic-tac-toe
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /img
  static_dir: static/img

- url: /.*
  script: play.app

libraries:
- name: jinja2
  version: 2.6
